### ISSUE TITLE
Logical bug

### ISSUE THREAD

**Issue by Kamuish** [jdavidrcamacho/StarSearch#8]
https://github.com/jdavidrcamacho/StarSearch/blob/0abcd81d5d0006a59838a030340d4f00cb3fab37/starsearch/phase3Archive.py#L838-L861

the if statement stars by evaluating  this:  (np.float32 or np.float64), which always translates to np.float32

then you are comparing the type of the variable against np.float32, which is not correct.

Either use isinstance   or np.isfinite or np.isnan

**Comment by jdavidrcamacho** [comment]
Fixed but still need to see what SIMBAD really gives me as starMag

**Comment by Kamuish** [comment]
I am almost sure that Simbad (through astroquery) returns a string (but don't quote me on that) with the mag value. Even if it returns a number, i think it would be better to use the np.isfinite  than to check for the variable type

**Comment by jdavidrcamacho** [comment]
I think you're right. Looking a bit more carefully in the code that line only show up after I check if the magnitude exists on simbad or not, so at that point the problem of being a number or nan should not exist anymore... i think :sweat_smile: I don't remember with which stars the problem was popping out
